version: '3.8'

services:
  web:
    build: .
    ports:
      - "${HOST_PORT:-4000}:${PORT:-4000}"
      - "11000:4369"
      - "11001:9999"
    depends_on:
      - db
    environment:
      - PORT
      - HOST_PORT
      - HOST
      - SECRET_KEY_BASE
      - LIVE_VIEW_SIGNING_SALT
      - GUARDIAN_SECRET_KEY
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - BALANCE_SNAPSHOT_ENABLED
      - BALANCE_SNAPSHOT_BTC_USD_VENUE
      - BALANCE_SNAPSHOT_BTC_USD_SYMBOL
      - BALANCE_SNAPSHOT_USD_QUOTE_VENUE
      - BALANCE_SNAPSHOT_USD_QUOTE_ASSET
      - DATABASE_URL

  db:
    image: postgres:13.1
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD

volumes:
  dbdata:
